2019-05-08 21:24:32,966 INFO: TalentSites Start [in C:\Users\eenan\Desktop\GraduateDesigner\code\GraduateDesigner\app\__init__.py:38]
2019-05-08 21:29:47,827 INFO: TalentSites Start [in C:\Users\eenan\Desktop\GraduateDesigner\code\GraduateDesigner\app\__init__.py:47]
2019-05-08 21:29:54,977 ERROR: Exception on / [GET] [in D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask_login\utils.py", line 260, in decorated_view
    return current_app.login_manager.unauthorized()
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask_login\login_manager.py", line 175, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask_login\utils.py", line 112, in login_url
    base = expand_login_view(login_view)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask_login\utils.py", line 89, in expand_login_view
    return url_for(login_view)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\werkzeug\routing.py", line 2181, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth.login'. Did you mean 'main.user' instead?
2019-05-08 21:33:31,417 INFO: TalentSites Start [in C:\Users\eenan\Desktop\GraduateDesigner\code\GraduateDesigner\app\__init__.py:47]
2019-05-08 21:33:37,102 ERROR: Exception on / [GET] [in D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask_login\utils.py", line 260, in decorated_view
    return current_app.login_manager.unauthorized()
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask_login\login_manager.py", line 175, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask_login\utils.py", line 112, in login_url
    base = expand_login_view(login_view)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask_login\utils.py", line 89, in expand_login_view
    return url_for(login_view)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\werkzeug\routing.py", line 2181, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth.login'. Did you mean 'main.user' instead?
2019-05-08 21:33:44,224 INFO: TalentSites Start [in C:\Users\eenan\Desktop\GraduateDesigner\code\GraduateDesigner\app\__init__.py:47]
2019-05-08 21:33:53,122 ERROR: Exception on / [GET] [in D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask_login\utils.py", line 260, in decorated_view
    return current_app.login_manager.unauthorized()
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask_login\login_manager.py", line 175, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask_login\utils.py", line 112, in login_url
    base = expand_login_view(login_view)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask_login\utils.py", line 89, in expand_login_view
    return url_for(login_view)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "D:\Users\eenan\Anaconda3\envs\nanmu\lib\site-packages\werkzeug\routing.py", line 2181, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth.login'. Did you mean 'main.user' instead?
2019-05-08 22:13:52,714 INFO: TalentSites Start [in C:\Users\eenan\Desktop\GraduateDesigner\code\GraduateDesigner\app\__init__.py:47]
2019-05-08 22:18:23,353 INFO: TalentSites Start [in C:\Users\eenan\Desktop\GraduateDesigner\code\GraduateDesigner\app\__init__.py:47]
2019-05-08 22:18:23,353 INFO: TalentSites Start [in C:\Users\eenan\Desktop\GraduateDesigner\code\GraduateDesigner\app\__init__.py:47]
2019-05-08 22:18:23,353 INFO: TalentSites Start [in C:\Users\eenan\Desktop\GraduateDesigner\code\GraduateDesigner\app\__init__.py:47]
